spring.application.name=my-portfolio-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db
spring.datasource.username=spring_user
spring.datasource.password=spring_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always